In [1]:
import tensorflow as tf

In [2]:
temp = [0., 0., 1., 0., 0., 2., 1., 0., 1., 0.]
values = tf.reshape(temp, [1,1,2,5])

In [5]:
print("TF version = " + tf.__version__)
values
# eager evaluation

TF version = 2.4.1


<tf.Tensor: shape=(1, 1, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 1., 0., 0.],
         [2., 1., 0., 1., 0.]]]], dtype=float32)>

In [1]:
%tensorflow_version 1.x
import tensorflow as tf
temp = [0., 0., 1., 0., 0., 2., 1., 0., 1., 0.]
values = tf.reshape(temp, [1,1,2,5])
print("TF version = " + tf.__version__)
values
# Lazy evaluation-> graph will be waited, and built later

TensorFlow 1.x selected.
TF version = 1.15.2


<tf.Tensor 'Reshape:0' shape=(1, 1, 2, 5) dtype=float32>

In [2]:
%tensorflow_version 2.x
import tensorflow as tf
temp = [0., 0., 1., 0., 0., 2., 1., 0., 1., 0.]
values = tf.reshape(temp, [1,1,2,5])


In [3]:
avgpool = tf.nn.pool(input=values, window_shape=(2,2), pooling_type='AVG', padding ='SAME')
maxpool=  tf.nn.pool(input=values, window_shape=(2,2), pooling_type='MAX', padding ='SAME')

In [4]:
avgpool

<tf.Tensor: shape=(1, 1, 2, 5), dtype=float32, numpy=
array([[[[1. , 0.5, 0.5, 0.5, 0. ],
         [2. , 1. , 0. , 1. , 0. ]]]], dtype=float32)>

In [5]:
maxpool

<tf.Tensor: shape=(1, 1, 2, 5), dtype=float32, numpy=
array([[[[2., 1., 1., 1., 0.],
         [2., 1., 0., 1., 0.]]]], dtype=float32)>

In [6]:
avgpool = tf.nn.pool(input=values, window_shape=(1,2), pooling_type='AVG', padding ='VALID')
maxpool=  tf.nn.pool(input=values, window_shape=(1,2), pooling_type='MAX', padding ='VALID')

In [7]:
avgpool

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1. , 0.5, 0.5, 0.5, 0. ]]]], dtype=float32)>

In [9]:
maxpool

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[2., 1., 1., 1., 0.]]]], dtype=float32)>